name: to_do_list
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.1
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.2.2
  google_fonts: ^4.0.3
  intl: ^0.18.1
  flutter_spinkit: ^5.2.0 # For animations
  lottie: ^2.6.0 # Optional for more advanced animations

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
